# .env
# RASA_X_VERSION=0.26.0
# RASA_VERSION=1.8.1
# RASA_SDK_VERSION=1.7.0
# RASA_X_PASSWORD=xyzzy
version: "3.4"

services:
  rasa-x:
    image: rasax:${RASA_X_VERSION}
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        - RASA_X_VERSION
    environment:
      - RASA_HOME=/app
      - RASA_X_PASSWORD=aida99
    ports:
      - "80:5005"
      - "443:5005"
      - "5002:5002"
    volumes:
      - ./:/app
    command: rasa x --no-prompt --endpoints endpoints.yml --credentials credentials-local.yml --port 5005 --cors "*" --debug
#    command: /app/rasax.sh
  app:
    image: rasa/rasa-sdk:${RASA_SDK_VERSION}
    #build:
    #  context: ./actions
    #  dockerfile: ./Dockerfile
    #  args:
    #    - RASA_SDK_VERSION
    volumes:
      - "./actions:/app/actions"
    ports:
      - "5055:5055"
  duckling:
    restart: always
    image: "rasa/duckling:latest"
    ports:
      - "8000:8000"
    command: ["duckling-example-exe", "--no-access-log", "--no-error-log"]
